# List of plugins
set -g @plugin "tmux-plugins/tmux-sensible"
set -g @plugin "catppuccin/tmux"

set -g base-index 1
set -g renumber-windows on
set -g mode-keys vi


# Options to make tmux more pleasant
set -g default-terminal "tmux-256color"

# Configure the catppuccin plugin
set -g @catppuccin_flavor "mocha"
set -g @catppuccin_window_status_style "rounded"
set -ogq @catppuccin_window_text " #W"
set -ogq @catppuccin_window_current_text " #W"



# Initialize tpack (keep this line at the very bottom of tmux.conf)
run 'tpack init'
