[mgr]
prepend_keymap = [
	{ on = "<C-o>", run = "shell --block --confirm 'nvim .'", desc = "Open current directory with neovim" },
	{ on = "<C-g>", run = "shell --block --confirm 'lazygit'", desc = "Open current directory with neovim" },
	{ on = "<C-t>", run = "shell --block --confirm '/bin/bash'", desc = "Open current directory with neovim" },
   	{ on = "f", run = "plugin fzf", desc = "Jump to a file/directory via fzf" },
	{ on = "F", run = "plugin zoxide", desc = "Jump to a directory via zoxide" },
    { on = "z", run = "filter", desc = "Filter help items" },
    { on = "D",         run = "remove",                      desc = "Trash selected files" },
	{ on = "d",         run = "remove --permanently",        desc = "Permanently delete selected files" },
]
