#/bin/bash -l

#######Bashrc set up###########
if [ -f "$HOME/dotconfigs/setup/shell_config.sh" ]; then
  source "$HOME/dotconfigs/setup/shell_config.sh" 
  echo "Using dotconfigs"
fi
##############################

######MODULES#######
source /usr/share/modules/init/bash
####################
