#!/bin/bash 

install_pkgs(){
	pixi global install nvim uv
}


echo "Creating symbolic links to bashrc, ibashrc, profile and nvim"
ln -sf ~/dotconfigs/setup/bashrc ~/.bashrc
ln -sf ~/dotconfigs/setup/ibashrc ~/.ibashrc
ln -sf ~/dotconfigs/setup/profile ~/.profile
mkdir -p ~/.config/nvim
ln -sf ~/dotconfigs/nvim/init.lua ~/.config/nvim/init.lua
ln -sf ~/dotconfigs/nvim/lua ~/.config/nvim/lua

if [ -x $HOME/.pixi/bin/pixi ]; then 
	echo "Pixi already installed"
	echo "Installing pkgs"
	install_pkgs
else
	echo "Installing pixi"
	curl -fsSL https://pixi.sh/install.sh | sh
	echo "Installing pkgs"
	install_pkgs
fi

if [ -f $HOME/.local/share/nvim/site/autoload/plug.vim ]; then
	echo "vim-plug is installed"
else	
	echo "vim-plug is not  installed"
	sh -c 'curl -fLo "${XDG_DATA_HOME:-$HOME/.local/share}"/nvim/site/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'
fi
