- name: setup
  hosts: localhost
  connection: local
  
  vars:
    home: "{{ansible_env.HOME}}"
    dir: "{{home}}/.local"
    bin: "{{home}}/.micromamba/bin"
    pkgs:
      - nvim
      - rust

  tasks:
    - name: "Show User"
      debug:
        msg: 'Ansible is running as: {{ansible_user_id}} and with $HOME: {{home}}'

    - name: 'Set {{dir}} and its subdirectories'
      file:
        path: "{{dir}}/{{item}}" 
        state: directory
        mode: "700"
      loop:
        - bin
        - lib
        - share
        - usr
        - state

    - name: 'Create ~/.micromamba'
      file:
        path: "{{home}}/.micromamba" 
        state: directory
        mode: "700"

    - name: "Check if micromamba is installed"
      stat:
        path: "{{bin}}/micromamba"
      register: micromamba_stat

    - name: "Install micromamba"
      when: not micromamba_stat.stat.exists
      block:

      - name: "Download micromamba.tar"
        get_url:
          url: "https://micro.mamba.pm/api/micromamba/linux-64/latest"
          use_netrc: false
          dest: "{{home}}/.micromamba/micromamba.tar"

      - name: "Extract micromamba"
        unarchive:
          src: "{{home}}/.micromamba/micromamba.tar"
          dest: "{{home}}/.micromamba"

      - name: "Remove micromamba.tar"
        file:
          path: "{{home}}/.micromamba/micromamba.tar"
          state: "absent"
      
      - name: "Micromamba bash init"
        shell: "{{home}}/.micromamba/bin/micromamba shell init -s bash -r {{home}}/.micromamba"
        args:
          executable: /bin/bash
    
    - name: "Get installed packages from micromamba"
      command: "{{ bin }}/micromamba list --json"
      register: mamba_list
      changed_when: false
    
    - name: "Extract installed package names" 
      set_fact:
        installed_pkgs: >-
          {{ (mamba_list.stdout | from_json)
             | map(attribute='name')
             | list }}

    - name: "Compute missing packages" 
      set_fact:
        missing_pkgs: "{{ pkgs | difference(installed_pkgs) }}"


    - name: "Install missing packages"
      command: >
        {{ bin }}/micromamba install -y conda-forge::
        {{ missing_pkgs | join(' ') }}
      when: missing_pkgs | length > 0
