#!/bin/bash 

install_pkgs(){
	pixi global install nvim uv
}


echo "Creating symbolic links to bashrc, ibashrc, profile and nvim"
ln -sf ~/dotconfigs/setup/bashrc ~/.bashrc
ln -sf ~/dotconfigs/setup/ibashrc ~/.ibashrc
ln -sf ~/dotconfigs/setup/profile ~/.profile
ln -sfn ~/dotconfigs/nvim ~/.config/nvim

if [ -x $HOME/.pixi/bin/pixi ]; then 
	echo "Pixi already installed"
	echo "Installing pkgs"
	install_pkgs
else
	echo "Installing pixi"
	curl -fsSL https://pixi.sh/install.sh | sh
	echo "Installing pkgs"
	install_pkgs
fi

if [ -d $HOME/.nvm ] && [ -d $HOME/.npm ] ; then
       echo "nvm and npm already installed"
else
      echo "Installing nvm"
      curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.4/install.sh | bash      
      export NVM_DIR="$HOME/.nvm"
      [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
      nvm install node
      nvm install-latest-npm
fi
